### ISSUE TITLE
MediaSDK fails to build with glibc 2.28

### ISSUE THREAD

**Issue by dbermond** [Intel-Media-SDK/MediaSDK#484]
I'm getting the following error when trying to build MediaSDK with the newly released glibc 2.28:
```
[ 79%] Building CXX object samples/metrics_monitor/CMakeFiles/test_monitor.dir/test/igt_load.cpp.o
/storage/linux/abs/intel-media-sdk-git/src/MediaSDK/samples/metrics_monitor/test/igt_load.cpp:30:10: fatal error: libio.h: No such file or directory
 #include <libio.h>
          ^~~~~~~~~
compilation terminated.
make[2]: *** [samples/metrics_monitor/CMakeFiles/test_monitor.dir/build.make:76: samples/metrics_monitor/CMakeFiles/test_monitor.dir/test/igt_load.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2072: samples/metrics_monitor/CMakeFiles/test_monitor.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

- It was building fine with glibc 2.27.

- glibc 2.28 no longer provides the header `libio.h`.

**System Information:**
**OS:** Arch Linux
**Compiler:** gcc 8.2.0
**glibc:** 2.28
**libva:** git master
**MediaSDK:** git master

**Comment by dvrogozh** [comment]
libio.h looks very strange. I guess this should be stdio.h.

**Comment by dvrogozh** [comment]
@dbermond : could you, please, try the above fix? I don't have your environment, so can't be 100% sure...

**Comment by dbermond** [comment]
@dvrogozh Thank you for the reply and for working on this issue.

I can confirm that you patch fixes it.

Tested in MediaSDK git master and in stable release 2018Q2.1. Both versions are building fine with glibc 2.28.

**Comment by dvrogozh** [comment]
Cool. @onabiull : can you, please, merge and cherry-pick to 2018Q2.1?

**Comment by onabiull** [comment]
Done: https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/MediaSDK-2018-Q2.2
