### ISSUE TITLE
Unable to build on Ubuntu 18.04 (undefined references to MFXTrace)

### ISSUE THREAD

**Issue by eldade** [Intel-Media-SDK/MediaSDK#272]
Not sure what I'm doing wrong here: I've configured cmake with the default settings (no --trace specified), but my build keeps failing with the errors below. I've tried release and debug, etc, as well as the latest snapshot of the code vs. the most recent release snapshot from April.

I'm completely new to the MediaSDK -- any hints would be much appreciated. Here's the output I'm seeing:

```
Building CXX object _studio/mfx_lib/plugin/CMakeFiles/mfx_vp8d_hw64.dir/__/decode/vp8/src/mfx_vp8_dec_decode_hw_vaapi.cpp.o
CMakeFiles/mfx_vp9d_hw64.dir/__/scheduler/src/mfx_scheduler_core_ischeduler.cpp.o: In function `mfxSchedulerCore::AddTask(MFX_TASK const&, _mfxSyncPoint**, char const*, int)':
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:588: undefined reference to `MFXTrace_DebugMessage'
CMakeFiles/mfx_vp9d_hw64.dir/__/scheduler/src/mfx_scheduler_core_ischeduler.cpp.o: In function `mfxSchedulerCore::Synchronize(mfxTaskHandle, unsigned int)':
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:304: undefined reference to `MFXTraceTask::~MFXTraceTask()'
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:304: undefined reference to `MFXTraceTask::MFXTraceTask(mfxTraceStaticHandle*, char const*, unsigned int, char const*, char*, mfxTraceLevel, char const*, bool)'
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:305: undefined reference to `MFXTrace_DebugMessage'
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:306: undefined reference to `MFXTrace_DebugMessage'
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:319: undefined reference to `MFXTraceTask::~MFXTraceTask()'
CMakeFiles/mfx_vp9d_hw64.dir/__/scheduler/src/mfx_scheduler_core_ischeduler.cpp.o: In function `mfxSchedulerCore::Synchronize(mfxTaskHandle, unsigned int)':
/home/eldade/msdk/_studio/shared/umc/core/vm_plus/include/umc_automatic_mutex.h:88: undefined reference to `MFXTraceTask::~MFXTraceTask()'
CMakeFiles/mfx_vp9d_hw64.dir/__/scheduler/src/mfx_scheduler_core_ischeduler.cpp.o: In function `mfxSchedulerCore::Synchronize(mfxTaskHandle, unsigned int)':
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_ischeduler.cpp:304: undefined reference to `MFXTraceTask::~MFXTraceTask()'
CMakeFiles/mfx_vp9d_hw64.dir/__/scheduler/src/mfx_scheduler_core_task_management.cpp.o: In function `mfxSchedulerCore::MarkTaskCompleted(MFX_CALL_INFO const*, unsigned int)':
/home/eldade/msdk/_studio/mfx_lib/scheduler/src/mfx_scheduler_core_task_management.cpp:621: undefined reference to `MFXTrace_DebugMessage'

```

Seems to me like if no `--trace` is specified, the `MFX_` macros shouldn't be pointing to anything, so I'm not sure why these references are even there.

**Comment by dvrogozh** [comment]
emm... difficult to comment knowing nothing on how you tried to build and where. Can you, please, provide:
1. Version of cmake you are using?
2. Commands you have ran trying to configure and build mediasdk?

If you will try to repeat your steps again, please, run `git clean -fdx` to avoid interleaving with prev. tries.

**Comment by adydychk** [comment]
@eldade Did you fix your problem?
Yesterday we started CI with gcc-8.1.0 on Ubuntu Server 18.04 and it works successful. If you have troubles try to build Media SDK with current master HEAD in opposite it is your local environment troubles.
