### ISSUE TITLE
Compile error: undefined reference to __cpu_model

### ISSUE THREAD

**Issue by uartie** [Intel-Media-SDK/MediaSDK#33]
Linking fails with both release and debug compilation...

Configure/Compile:
```
perl tools/builder/build_mfx.pl --no-warn-as-error --cmake=intel64.make.debug
make -C __cmake/intel64.make.debug
```

Output:
```
I am going to execute:
  cmake --no-warn-unused-cli -Wno-dev -G "Unix Makefiles" -D__GENERATOR:STRING=make -DCMAKE_CONFIGURATION_TYPES:STRING="release;debug" -DCMAKE_BUILD_TYPE:STRING=debug -D__ARCH:STRING=intel64 -D__CONFIG:STRING=debug -D__IPP:STRING=e9 -D__TARGET_PLATFORM:STRING=BDW /home/uaeoff/Work/workspace/media/src/msdk
[ cmd ]: cmake --no-warn-unused-cli -Wno-dev -G "Unix Makefiles" -D__GENERATOR:STRING=make -DCMAKE_CONFIGURATION_TYPES:STRING="release;debug" -DCMAKE_BUILD_TYPE:STRING=debug -D__ARCH:STRING=intel64 -D__CONFIG:STRING=debug -D__IPP:STRING=e9 -D__TARGET_PLATFORM:STRING=BDW /home/uaeoff/Work/workspace/media/src/msdk
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenCL was found here: /usr/lib64 and /usr/include
-- CMAKE_INSTALL_PREFIX=/opt/intel/mediasdk
-- Intel(R) Media SDK was found here /home/uaeoff/Work/workspace/media/src/msdk
-- Enabling API 1.25 feature set with flags 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.3.12") 
-- Checking for module 'libva>=0.33'
--   Found libva, version 1.0.0
-- Checking for module 'libdrm'
--   Found libdrm, version 2.4.89
-- Checking for module 'libva-drm>=0.33'
--   Found libva-drm, version 1.0.0
-- Checking for module 'x11'
--   Found x11, version 1.6.5
-- Checking for module 'libva-x11>=0.33'
--   Found libva-x11, version 1.0.0
-- Global Configuration of Targets
-- Target Architecture to compile: sse4.2
-- CMAKE_INSTALL_PREFIX=/opt/intel/mediasdk
-- MFX_PLUGINS_DIR=/opt/intel/mediasdk/plugins
-- MFX_MODULES_DIR=/opt/intel/mediasdk/lib64
-- OpenCL was found here: /usr/lib64 and /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/uaeoff/Work/workspace/media/src/msdk/__cmake/intel64.make.debug

...

[ 66%] Linking CXX shared library ../../__bin/debug/libmfxhw64_d.so
cd /home/uaeoff/Work/workspace/media/src/msdk/__cmake/intel64.make.debug/_studio/mfx_lib && /usr/bin/cmake -E cmake_link_script CMakeFiles/mfxhw64_d.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -msse4.2 -std=c++11 -m64 -g -pipe -fPIC -O0 -Wall -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-unused  -Wformat -Wformat-security -g -D_DEBUG -L/home/uaeoff/Work/workspace/media/install/lib -Wl,--no-undefined,-z,relro,-z,now,-z,noexecstack -Wl,--default-symver -Wl,--version-script=/home/uaeoff/Work/workspace/media/src/msdk/_studio/mfx_lib/libmfx.map -fstack-protector   -Wl,--no-undefined,-z,relro,-z,now,-z,noexecstack -fstack-protector  -L/home/uaeoff/Work/workspace/media/install/lib -shared -Wl,-soname,libmfxhw64_d.so -o ../../__bin/debug/libmfxhw64_d.so CMakeFiles/mfxhw64_d.dir/scheduler/src/mfx_scheduler_core.cpp.o CMakeFiles/mfxhw64_d.dir/scheduler/src/mfx_scheduler_core_ischeduler.cpp.o CMakeFiles/mfxhw64_d.dir/scheduler/src/mfx_scheduler_core_iunknown.cpp.o CMakeFiles/mfxhw64_d.dir/scheduler/src/mfx_scheduler_core_task.cpp.o CMakeFiles/mfxhw64_d.dir/scheduler/src/mfx_scheduler_core_task_management.cpp.o CMakeFiles/mfxhw64_d.dir/scheduler/src/mfx_scheduler_core_thread.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_async.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_decode.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_enc.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_encode.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_pak.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_plugin.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_query.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_session.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/libmfxsw_vpp.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/mfx_session.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/mfx_user_plugin.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/mfx_brc_common.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/mfx_mpeg2_dec_common.cpp.o CMakeFiles/mfxhw64_d.dir/shared/src/mfx_vc1_dec_common.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/cm_mem_copy.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/mfx_vpp_vaapi.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/libmfx_allocator.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/libmfx_allocator_vaapi.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/libmfx_core.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/libmfx_core_factory.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/libmfx_core_vaapi.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/mfx_umc_alloc_wrapper.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/mfx_static_assert_structs.cpp.o CMakeFiles/mfxhw64_d.dir/__/shared/src/mfx_mfe_adapter.cpp.o -Xlinker --start-group ../../__lib/debug/libmfx_trace_hw.a ../../__lib/debug/libbitrate_control.a ../../__lib/debug/libh264_dec_hw.a ../../__lib/debug/libjpeg_common.a ../../__lib/debug/libjpeg_dec_hw.a ../../__lib/debug/libmpeg2_dec_hw.a ../../__lib/debug/libumc.a ../../__lib/debug/libvm.a ../../__lib/debug/libvm_plus.a ../../__lib/debug/libumc_va_hw.a ../../__lib/debug/libcmrt_cross_platform_hw.a ../../__lib/debug/libdecode_hw.a ../../__lib/debug/libencode_hw.a ../../__lib/debug/libh264_la.a ../../__lib/debug/libgenx_h264_encode_embeded.a ../../__lib/debug/libmfx_common.a ../../__lib/debug/libmfx_common_hw.a ../../__lib/debug/libvpp_hw.a ../../__lib/debug/libh264_common.a ../../__lib/debug/libh264_preenc.a ../../__lib/debug/libh264_enc.a ../../__lib/debug/libh264_pak.a ../../__lib/debug/libvc1_common.a ../../__lib/debug/libvc1_dec_hw.a ../../__lib/debug/libmfx_trace.a -lpthread -ldl -lva ../../__lib/debug/libSafeString.a -Xlinker --end-group 
../../__lib/debug/libencode_hw.a(mfx_h264_scd.cpp.o): In function `MfxHwH264Encode::CpuFeature_SSE41()':
/home/uaeoff/Work/workspace/media/src/msdk/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_scd.cpp:578: undefined reference to `__cpu_model'
../../__lib/debug/libencode_hw.a(mfx_h264_scd.cpp.o): In function `MfxHwH264Encode::CpuFeature_AVX2()':
/home/uaeoff/Work/workspace/media/src/msdk/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_scd.cpp:582: undefined reference to `__cpu_model'
../../__lib/debug/libvpp_hw.a(mfx_scd.cpp.o): In function `SceneChangeDetector::Init(int, int, int, unsigned int, CmDevice*)':
/home/uaeoff/Work/workspace/media/src/msdk/_studio/shared/src/mfx_scd.cpp:12008: undefined reference to `__cpu_model'
collect2: error: ld returned 1 exit status
make[2]: *** [_studio/mfx_lib/CMakeFiles/mfxhw64_d.dir/build.make:904: __bin/debug/libmfxhw64_d.so] Error 1
make[2]: Leaving directory '/home/uaeoff/Work/workspace/media/src/msdk/__cmake/intel64.make.debug'
make[1]: *** [CMakeFiles/Makefile2:519: _studio/mfx_lib/CMakeFiles/mfxhw64_d.dir/all] Error 2
make[1]: Leaving directory '/home/uaeoff/Work/workspace/media/src/msdk/__cmake/intel64.make.debug'
make: *** [Makefile:133: all] Error 2
make: Leaving directory '/home/uaeoff/Work/workspace/media/src/msdk/__cmake/intel64.make.debug'
```

Environment:
```
libva (master) heads/master-0-gfbed1dbb5bfc 
gmmlib (master) heads/master-0-g0154744f9c2d
intel-media-driver (master) heads/master-0-g87b133062dee
msdk (master) heads/master-0-gfce107957ad4

gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)

SKL Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
```

**Comment by uartie** [comment]
On Ubuntu 14.04 LTS w/gcc 4.8.4 and dlopen fix from #34... this compiles fine.  But still fails to compile on Fedora 26/27 and Ubuntu 16.04 LTS with gcc 7.2.1 and 5.4.0, respectively.

**Comment by liumark** [comment]
I got the same issue on Ubuntu 16.04, GCC 5.4 with the same hardware platform. 

Although I have following work around:
--Add the  following line to ~/builder/FindFunctions.cmake at line #296 (https://github.com/Intel-Media-SDK/MediaSDK/blob/master/builder/FindFunctions.cmake#L296):
    if(CMAKE_COMPILER_IS_GNUCC AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 5.0 AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0)
      target_link_libraries(${target} gcc_s gcc)
    endif()

I also tried the gcc 6 but the build failed on the other issues before reaching to this point.

Mark

**Comment by ruiling** [comment]
you can take a try #21, it is said that gcc 5& 6 have this issue, I am not sure about gcc7.

**Comment by dbermond** [comment]
It still does not build with gcc 6.4.1 by using the changes implemented in #21 for me.

The changes implemented in #21 only fix compilation with gcc 5.5.0 for me.

gcc7 still not usable.

System: Arch Linux x86_64.

**Comment by c3d** [comment]
I built successfully on Fedora 27 using gcc 7.2.1 with the following change: https://github.com/c3d/MediaSDK/commit/489d0bbd561632161ff3457020c64cc894500a3e.

**Comment by adydychk** [comment]
@uarie Is you problem still relevant? Since January we pushed a lot of commits and also we already use gcc 6.3.1 in GitHub CI.
