### PR TITLE
[21.3.0 vs. 21.3.1 regression] Unbreak build on IA32

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by #2692. From [error log](https://github.com/Intel-Media-SDK/MediaSDK/files/6949089/intel-media-sdk-21.3.1.log):
```c++
api/mfx_dispatch/linux/mfxloader.cpp:193:23: error: use of undeclared identifier 'ONEVPLRT'
    libs.emplace_back(ONEVPLRT);
                      ^
api/mfx_dispatch/linux/mfxloader.cpp:194:43: error: expected ')'
    libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
                                          ^
api/mfx_dispatch/linux/mfxloader.cpp:194:22: note: to match this '('
    libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
                     ^
api/mfx_dispatch/linux/mfxloader.cpp:213:23: error: use of undeclared identifier 'ONEVPLRT'
    libs.emplace_back(ONEVPLRT);
                      ^
api/mfx_dispatch/linux/mfxloader.cpp:214:43: error: expected ')'
    libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
                                          ^
api/mfx_dispatch/linux/mfxloader.cpp:214:22: note: to match this '('
    libs.emplace_back(MFX_MODULES_DIR "/" ONEVPLRT);
                     ^
4 errors generated.
```

### CODE REVIEW

**Review by dvrogozh — APPROVED** [review]
Thanks for spotting. LGTM.

**Review by dmitryermilov — APPROVED** [review]
