### ISSUE TITLE
compiler error: ‘MFX_EXTBUFF_VPP_COLOR_CONVERSION’ was not declared in this scope

### ISSUE THREAD

**Issue by ruiling** [Intel-Media-SDK/MediaSDK#38]
I failed to compile on ubuntu 16.04 with below error:
/home/ocl/projects/MediaSDK/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:4717:26: error: ‘MFX_EXTBUFF_VPP_COLOR_CONVERSION’ was not declared in this scope
                 else if (MFX_EXTBUFF_VPP_COLOR_CONVERSION == bufferId)
                          ^
/home/ocl/projects/MediaSDK/_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp:4719:50: error: ‘MFX_CHROMA_SITING_UNKNOWN’ was not declared in this scope
                     executeParams.chromaSiting = MFX_CHROMA_SITING_UNKNOWN;
                                                  ^
_studio/mfx_lib/vpp/CMakeFiles/vpp_hw.dir/build.make:89: recipe for target '_studio/mfx_lib/vpp/CMakeFiles/vpp_hw.dir/src/mfx_vpp_hw.cpp.o' failed

**Comment by ruiling** [comment]
I finally find out the reason is I once installed an old version header files to /usr/include/. and the build scripts finds that old version and then report compile error. after removing old version header files under /usr/include/, the compile error disappear.
