### ISSUE TITLE
build fails with g++ 7.2/7.3 when using the default options 

### ISSUE THREAD

**Issue by xhaihao** [Intel-Media-SDK/MediaSDK#84]
The code fails to build with g++ 7.2/7.3 when using the default options

> /MediaSDK/api/opensource/mfx_dispatch/src/main.cpp: In function ‘mfxStatus disp_MFXVideoUSER_Load(mfxSession, const mfxPluginUID*, mfxU32)’:
> /MediaSDK/api/opensource/mfx_dispatch/src/main.cpp:563:11: error: the compiler can assume that the address of ‘pHandle’ will never be NULL [-Werror=address]
>      if (!&pHandle)
>            ^~~~~~~

User may work around this issue by using --no-warn-as-error

**Comment by xhaihao** [comment]
g++ 7.2 is the latest version on Ubuntu 17.10 and g++7.3 is the latest version on Clear Linux OS

**Comment by artem-shaporenko** [comment]
I think it is just a bug in verification implementation, thanks @xhaihao.

**Comment by xhaihao** [comment]
There are lots of other errors besides the above errors. It would be better not to take all warnings as errors by default because strict compilation flags are not consistent across different versions of GCC

**Comment by onabiull** [comment]
This is nice idea. I'll add check which would relax compilation flags for GCC versions other than CI baseline.

**Comment by artem-shaporenko** [comment]
from one side - agree it'll be easier, from another side - treating warning as error was added specifically to make developers not to create buggy code, so much better to fix such issues...

**Comment by xhaihao** [comment]
Is it possible to provide an option for developers to use strict compilation? End-user may use the default options without strict compilation flags.

**Comment by lubagov** [comment]
gcc-6 Ubuntu 6.2.0-5ubuntu12, same error...

**Comment by DavidMarec** [comment]
What this was supposed to to ?

file `/api/opensource/mfx_dispatch/src/main.cpp` :

```C++
 MFX_DISP_HANDLE &pHandle = *(MFX_DISP_HANDLE *) session;
    if (&pHandle=NULL)
    {
        DISPATCHER_LOG_ERROR((("MFXVideoUSER_Load: session=NULL\n")));
        return MFX_ERR_NULL_PTR;
    }
````
`pHandle` is a c++ reference, it can't be a nullptr ...
If I understand it well, passing a null pointer to `session`, will only crash the process because of the null pointer dereferencing the line before ...

Check out for session first:
```C++
if(session==nullptr){
...}
MFX_DISP_HANDLE &pHandle = *(MFX_DISP_HANDLE *) session;
````

**Comment by DavidMarec** [comment]
see #119

**Comment by xhaihao** [comment]
I still see the following error when building the latest master. 

/home/xhh/graphics/ex/vaapi/MediaSDK/_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_slice_hw.cpp: In member function ‘virtual void UMC::MPEG2VideoDecoderHW::quant_matrix_extension(int)’:
/home/xhh/graphics/ex/vaapi/MediaSDK/_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_dec_slice_hw.cpp:561:86: error: ‘q_matrix[3][i]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
               pack_l.QmatrixData.chroma_non_intra_quantiser_matrix[i] = q_matrix[3][i];
                                                                         ~~~~~~~~~~~~~^
cc1plus: all warnings being treated as errors

**Comment by xhaihao** [comment]
Fixed by the commit below

commit 6c0558c3912799fc9ee694be44c6bbd25d41b0c4
Author: Dmitry Ermilov <dmitry.ermilov@intel.com>
Date:   Thu May 10 05:39:23 2018 -0400

    [mpeg2d] q_matrix zero initilizatioin
